version: "3"

services:
  backend:
    env_file:
        "./server/env.json"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "hotspot-backend"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "hotspot-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"